MONGO_HOST = '103.35.64.122'
MONGO_PORT = 2200
MONGO_USER = 'dbMongo'
MONGO_PASS = 'SOh3TbYhx8ypJPxmt1oOfL'

MONGO_DB = 'dbMongo'

MONGO_COLLECTION_ARTICLES = 'articles'
MONGO_COLLECTION_HOT_EVENTS = 'hot_events'
MONGO_COLLECTION_SUMMRIES = 'summaries'