MONGO_HOST = '45.32.121.120'
MONGO_PORT = 27017
MONGO_USER = ''
MONGO_PASS = ''

MONGO_DB = 'dbMongo'

MONGO_COLLECTION_ARTICLES = 'articles'
MONGO_COLLECTION_HOT_EVENTS = 'hot_events'
MONGO_COLLECTION_SUMMRIES = 'summaries'